name: .Net App CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Set up .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'  # Adjust to your .NET version
    
    # Step 3: Restore NuGet packages
    - name: Restore dependencies
      run: dotnet restore
    
    # Step 4: Build the .NET project
    - name: Build project
      run: dotnet build --configuration Release
    
    # Step 5: Run unit tests
    - name: Run tests
      run: dotnet test --configuration Release   
